### ISSUE TITLE
Delete account

### ISSUE THREAD

**Issue by matthewl** [matthewl/Markcase#22]
Allow the user to delete the account.

In the preferences pages, add a button (plus confirmation) at the bottom of the page to delete their account. The account, bookmarks, bundles and taggings should be deleted.

Add some text in the confirmation to signal the effect of the delete action including the loss of all data. A modal for this might be an option, as well as typing in 'delete' to confirm the delete action.

## Tasks

- [x] Ensure the delete process is working from the account model down to its dependents (bundles, bookmarks and taggings).
- [x] Add a delete button to the bottom of the preferences section.
- [x] Confirm the delete action with a modal. Only a confirmation here will be accepted.
- [x] Once accepted, delete all the user's bookmarks and redirect to the login screen.
