### ISSUE TITLE
Staggered registrations

### ISSUE THREAD

**Issue by matthewl** [matthewl/Markcase#9]
Allow registrations to be opened up for a period of time, once the number of accounts has reached a number, disable the registration screen. This only applies to multi-account installations. There is no registration screen for single-account installations.

## Tasks

- [x] If the setting is for a single account, redirect to the home page with a message.
- [ ] Create a feature toggle for the registration screen, that only allows the registration form to display when the number of accounts is below a certain level.
- [x] Allow a user to register with a login, email and password. Upon successful registration redirect the user to their own bookmarks page.
